[package]
name = "sq3_derive"
edition.workspace = true
rust-version.workspace = true
version.workspace = true
description.workspace = true
readme.workspace = true
keywords.workspace = true
license.workspace = true
repository.workspace = true

[lib]
proc-macro = true

[dependencies]
